export default {
  USER_STATUS_CHANGED: 'USER // STATUS CHANGED',
  VIDEOS_FETCHED: 'VIDEOS // FETCHED',
  VIDEO_CREATED: 'VIDEOS // CREATED',
  VIDEO_UPDATED: 'VIDEOS // UPDATED',
  VIDEO_DELETED: 'VIDEOS // DELETED'
}